---

- name: Setup DBserver
  hosts: dbsrvgrp
  become: yes
  tasks:
          - name: Install MYSQL server
            yum:
                    name: mariadb-server
                    state: present

          - name: Install python MySQL
            yum:
                    name: MySQL-python
                    state: present

          - name: Start & Enable MariaDB server
            service:
                    name: mariadb
                    state: started
                    enabled: yes
          - name: Create a new database with name 'Accounts'
            mysql_db:
                    name: accounts
                    state: present
          - name: Create database user with name 'admin'
            mysql_user:
                    name: admin
                    password: 12345
                    priv: '*.*:ALL'
                    state: present
