- name: understanding precedence of variables
  hosts: all
  become: yes
  vars:
        USRNM: playuser
        COMM: variable from playbook
  tasks:
          - name: create a USER
            user:
                    name: "{{USRNM}}"
                    comment: "{{COMM}}"
            register: USROUT

          - debug:
                  var: USROUT.name

          - debug:
                  var: USROUT.comment
                        
