# handlers file post-install


- name: Restart Ntp on debian
  service:
          name: ntp
          state: restarted
          enabled: yes
          when: ansible_os_family == "Debian"

- name: Restart Ntp on redhat
  service:
          name: ntpd
          state: restarted
          enabled: yes
          when: ansible_os_family == "RedHat"
